#spring.application.name=categoryservice
#
#server.port=5003

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3307/categorydb
#spring.datasource.username=root
#spring.datasource.password=testtest
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server:
  port: 5003

spring:
  application:
    name: categoryservice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/categorydb
    username: root
    password: testtest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  #      hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/